min-version: v0.12.0
formatter: default
rules:
  - header-min-length
  - header-max-length
  - type-enum
severity:
  default: error
settings:
  header-min-length:
    argument: 10
  header-max-length:
    argument: 100
  type-enum:
    argument:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - test
