// Package publicstatus renders and checks the release-backed public status
// section of README.md from CATALOG.yml and docs/release-evidence.yml, so the
// public documentation never claims lifecycle status, versions, preview
// stability, or pinned installation that the catalog and retained release
// evidence do not support. See docs/public-skill-status.md for the contract.
package publicstatus

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Markers bound the generated public status section in README.md. The section
// is regenerated by cmd/generate-public-status and verified by the
// check-public-status repository check. Everything between (and including)
// the markers must equal a fresh render, so stale derived documentation is
// rejected instead of silently repaired.
const (
	beginningMarker = "<!-- BEGIN generated: public-status -->"
	endingMarker    = "<!-- END generated: public-status -->"
)

// entryPoints are the evaluated outcome-oriented entry points named by
// Issue 175. Direct primitive invocation remains documented for advanced or
// partial workflows.
var entryPoints = []string{"improve-project", "deliver-change", "resolve-defect"}

// catalogEntry is one authoritative CATALOG.yml skill entry.
type catalogEntry struct {
	Name    string `yaml:"name"`
	Summary string `yaml:"summary"`
	Status  string `yaml:"status"`
	Version string `yaml:"version"`
}

// ReleaseEvidence is the retained release record written by the release flow
// (Issue 174) only after a tag is verified and published.
type ReleaseEvidence struct {
	Released   bool   `yaml:"released"`
	Tag        string `yaml:"tag"`
	ReleaseURL string `yaml:"release_url"`
	Commit     string `yaml:"commit"`
}

// authorityDoc is the committed contract whose presence check-public-status
// enforces alongside the generated section.
const authorityDoc = "docs/public-skill-status.md"

// Render builds the public status section, including its markers, from the
// two authorities. It returns an error when the authorities cannot support
// the documented claims: a missing entry point, a partially filled evidence
// record, or a released tag version that contradicts the catalog.
func Render(catalogContent, evidenceContent []byte) (string, error) {
	var doc struct {
		Skills []catalogEntry `yaml:"skills"`
	}
	if err := yaml.Unmarshal(catalogContent, &doc); err != nil {
		return "", fmt.Errorf("CATALOG.yml cannot be parsed: %w", err)
	}
	catalog := map[string]catalogEntry{}
	for _, entry := range doc.Skills {
		if entry.Name != "" {
			catalog[entry.Name] = entry
		}
	}
	var evidence ReleaseEvidence
	if err := yaml.Unmarshal(evidenceContent, &evidence); err != nil {
		return "", fmt.Errorf("docs/release-evidence.yml cannot be parsed: %w", err)
	}

	for _, name := range entryPoints {
		if _, ok := catalog[name]; !ok {
			return "", fmt.Errorf("entry point %s is missing from CATALOG.yml", name)
		}
	}
	if err := validateEvidence(evidence, catalog); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(beginningMarker)
	b.WriteString("\n\n## Public status\n\n")
	b.WriteString("This section is generated from `CATALOG.yml` and `docs/release-evidence.yml` by `mise run generate:public-status` and mechanically verified by `check:repository`. Do not edit by hand. See [`docs/public-skill-status.md`](docs/public-skill-status.md) for the authority and evidence contract.\n\n")
	b.WriteString("### Outcome-oriented entry points\n\n")
	b.WriteString("The evaluated entry points coordinate the primitive skills from a user request to a complete observable result; direct primitive invocation remains available for advanced or partial workflows.\n\n")
	b.WriteString("| Entry point | Outcome | Status | Version |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, name := range entryPoints {
		entry := catalog[name]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", name, entry.Summary, entry.Status, entry.Version)
	}
	b.WriteString("\n### Preview stability\n\n")
	b.WriteString(stabilitySentence(catalog))
	b.WriteString("\n\n")
	b.WriteString(releaseSentence(evidence))
	b.WriteString("\n\n### Pinned installation\n\n")
	if evidence.Released {
		b.WriteString(fmt.Sprintf("The verified preview release is `%s` (commit `%s`). Pin any cataloged skill or entry point for Codex and Claude Code, for example:\n\n```bash\n", evidence.Tag, evidence.Commit))
		for _, agent := range []string{"codex", "claude-code"} {
			fmt.Fprintf(&b, "gh skill install hidekitux/skills <skill>@%s --agent %s --scope user\n", evidence.Tag, agent)
		}
		b.WriteString("```\n")
	} else {
		b.WriteString("Pinned installation is documented from retained release evidence only. No verified release exists yet, so no pinned installation is claimed; the release flow ([Issue #174](https://github.com/hidekitux/skills/issues/174)) records the preview tag, commit, and Codex and Claude Code installation results in `docs/release-evidence.yml` before this section can state them.\n")
	}
	b.WriteString(endingMarker)
	return b.String(), nil
}

// validateEvidence rejects release evidence that cannot back the documented
// claims: a released tag contradicting the catalog versions, a partially
// filled released record, or a filled record that is not marked released.
func validateEvidence(evidence ReleaseEvidence, catalog map[string]catalogEntry) error {
	if evidence.Released {
		if evidence.Tag == "" || evidence.ReleaseURL == "" || evidence.Commit == "" {
			return fmt.Errorf("docs/release-evidence.yml is released but tag, release_url, or commit is empty")
		}
		version := strings.TrimPrefix(evidence.Tag, "v")
		for _, entry := range catalog {
			if entry.Version != version {
				return fmt.Errorf("release tag %s version %q does not match catalog version %q of %s; align every catalog version or publish a new release (Issue #174)", evidence.Tag, version, entry.Version, entry.Name)
			}
		}
		return nil
	}
	if evidence.Tag != "" || evidence.ReleaseURL != "" || evidence.Commit != "" {
		return fmt.Errorf("docs/release-evidence.yml records release fields while released is false")
	}
	return nil
}

// stabilitySentence describes preview stability from the catalog statuses.
func stabilitySentence(catalog map[string]catalogEntry) string {
	statuses := map[string]bool{}
	for _, entry := range catalog {
		statuses[entry.Status] = true
	}
	if len(statuses) == 1 {
		for status := range statuses {
			if status == "experimental" {
				return "Every cataloged skill is `experimental` until behavioral and release evidence qualify promotion ([docs/evaluation.md](docs/evaluation.md))."
			}
			return fmt.Sprintf("Every cataloged skill is `%s` as recorded in `CATALOG.yml`; promotion and demotion follow the behavioral evaluation threshold ([docs/evaluation.md](docs/evaluation.md)).", status)
		}
	}
	names := make([]string, 0, len(statuses))
	for status := range statuses {
		names = append(names, "`"+status+"`")
	}
	sort.Strings(names)
	return "Cataloged skills are " + joinList(names) + " as recorded in `CATALOG.yml`; `stable` requires retained behavioral-evaluation evidence ([docs/evaluation.md](docs/evaluation.md))."
}

// releaseSentence states the verified release from retained evidence, or the
// absence of one (Issue 174).
func releaseSentence(evidence ReleaseEvidence) string {
	if evidence.Released {
		return fmt.Sprintf("Verified release: `%s` ([GitHub Release](%s), commit `%s`).", evidence.Tag, evidence.ReleaseURL, evidence.Commit)
	}
	return "No verified release exists yet ([Issue #174](https://github.com/hidekitux/skills/issues/174)); until the preview release is published, any `@vX.Y.Z` installation resolves to the default branch head."
}

// joinList formats a short list of backticked items for prose.
func joinList(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	}
	return strings.Join(items[:len(items)-1], ", ") + ", and " + items[len(items)-1]
}

// Check validates the committed public status section against a fresh render
// and the presence of the authority document. It returns 0 on success or 1
// when the documentation drifts.
func Check(root string, out, errOut io.Writer) int {
	findings := []string{}
	read := func(rel string) string {
		content, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			findings = append(findings, rel+" is missing")
			return ""
		}
		return string(content)
	}
	catalog := read("CATALOG.yml")
	evidence := read(filepath.Join("docs", "release-evidence.yml"))
	readme := read("README.md")
	read(filepath.Join(authorityDoc))
	if len(findings) > 0 {
		sort.Strings(findings)
		fmt.Fprintln(errOut, "Public-status check failed:")
		for _, finding := range findings {
			fmt.Fprintf(errOut, "- %s\n", finding)
		}
		return 1
	}

	rendered, renderErr := Render([]byte(catalog), []byte(evidence))
	if renderErr != nil {
		findings = append(findings, renderErr.Error())
	} else if committed := committedBlock(readme); committed == "" {
		findings = append(findings, "README.md is missing the public-status markers (BEGIN/END generated: public-status); run mise run generate:public-status")
	} else if committed != rendered {
		findings = append(findings, "README.md public status section is stale; run mise run generate:public-status")
		findings = append(findings, describeDrift(committed, rendered)...)
	}
	sort.Strings(findings)
	if len(findings) > 0 {
		fmt.Fprintln(errOut, "Public-status check failed:")
		for _, finding := range findings {
			fmt.Fprintf(errOut, "- %s\n", finding)
		}
		return 1
	}
	fmt.Fprintln(out, "Public-status check passed: the generated public status section matches the catalog and release evidence.")
	return 0
}

// committedBlock returns the README text between the BEGIN and END markers,
// inclusive, or "" when either marker is missing.
func committedBlock(readme string) string {
	start := strings.Index(readme, beginningMarker)
	if start < 0 {
		return ""
	}
	rest := readme[start+len(beginningMarker):]
	end := strings.Index(rest, endingMarker)
	if end < 0 {
		return ""
	}
	return readme[start : start+len(beginningMarker)+end+len(endingMarker)]
}

// describeDrift returns up to five line differences that caused the committed
// section to be stale, so the finding stays actionable.
func describeDrift(committed, rendered string) []string {
	want := strings.Split(rendered, "\n")
	got := strings.Split(committed, "\n")
	notes := []string{}
	max := len(want)
	if len(got) > max {
		max = len(got)
	}
	for i := 0; i < max && len(notes) < 5; i++ {
		w, g := "", ""
		if i < len(want) {
			w = want[i]
		}
		if i < len(got) {
			g = got[i]
		}
		if w != g {
			notes = append(notes, fmt.Sprintf("line %d differs: expected %q, got %q", i+1, w, g))
		}
	}
	if len(notes) == 0 {
		notes = append(notes, "expected and committed sections differ only in trailing whitespace")
	}
	return notes
}

// Write regenerates the public status section in README.md in place and
// returns 0 on success. It inserts the section before the "## Development
// workflow" heading when the markers are absent, and appends at the end as a
// fallback, so the first run bootstraps the committed artifact.
func Write(root string, out, errOut io.Writer) int {
	catalog, err := os.ReadFile(filepath.Join(root, "CATALOG.yml"))
	if err != nil {
		fmt.Fprintf(errOut, "generate-public-status: cannot read CATALOG.yml: %v\n", err)
		return 1
	}
	evidence, err := os.ReadFile(filepath.Join(root, "docs", "release-evidence.yml"))
	if err != nil {
		fmt.Fprintf(errOut, "generate-public-status: cannot read docs/release-evidence.yml: %v\n", err)
		return 1
	}
	rendered, renderErr := Render(catalog, evidence)
	if renderErr != nil {
		fmt.Fprintf(errOut, "generate-public-status: %v\n", renderErr)
		return 1
	}
	readmePath := filepath.Join(root, "README.md")
	readme, err := os.ReadFile(readmePath)
	if err != nil {
		fmt.Fprintf(errOut, "generate-public-status: cannot read README.md: %v\n", err)
		return 1
	}
	updated := replaceBlock(string(readme), rendered)
	if updated == string(readme) {
		fmt.Fprintln(out, "Public status section is already current; no change.")
		return 0
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		fmt.Fprintf(errOut, "generate-public-status: cannot write README.md: %v\n", err)
		return 1
	}
	fmt.Fprintln(out, "Regenerated the public status section in README.md.")
	return 0
}

// replaceBlock replaces the existing marker-bounded section, or inserts the
// rendered block before "## Development workflow" (appending at the end as a
// fallback) when the markers are absent.
func replaceBlock(readme, block string) string {
	start := strings.Index(readme, beginningMarker)
	if start >= 0 {
		rest := readme[start+len(beginningMarker):]
		if end := strings.Index(rest, endingMarker); end >= 0 {
			stop := start + len(beginningMarker) + end + len(endingMarker)
			return readme[:start] + block + readme[stop:]
		}
	}
	anchor := "## Development workflow"
	idx := strings.Index(readme, anchor)
	if idx < 0 {
		sep := ""
		if readme != "" && !strings.HasSuffix(readme, "\n") {
			sep = "\n"
		}
		return readme + sep + "\n" + block + "\n"
	}
	return readme[:idx] + block + "\n\n" + readme[idx:]
}
