#!/usr/bin/env python3
"""Require README FSL and test badges to be auto-updating endpoint badges.

The FSL mutation badges, the fslc-version badge, and the test badges are
generated by the Badge data workflow from the `badge-data` branch, so the
README must reference the shields.io endpoint payloads rather than hand-written
static badges. This check fails when any of the six required payloads is not
referenced by a README endpoint badge.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.parse
from pathlib import Path

BADGE_URL_PREFIX = "https://raw.githubusercontent.com/hidekitux/skills/badge-data/"
ENDPOINT_BADGE = re.compile(
    r"!\[[^\]]+\]\(https://img\.shields\.io/endpoint\?url=([^)\s]+)\)"
)
REQUIRED_PAYLOADS = (
    "fsl-killed.json",
    "fsl-kill-rate.json",
    "fsl-survived.json",
    "fslc-version.json",
    "tests-status.json",
    "tests-run.json",
)


def main_with_root(root: Path) -> int:
    root = root.resolve()
    path = root / "README.md"
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        print(
            f"Badge check failed: cannot read {path.relative_to(root)}: {exc}",
            file=sys.stderr,
        )
        return 1

    referenced: set[str] = set()
    errors: list[str] = []
    for match in ENDPOINT_BADGE.finditer(text):
        url = urllib.parse.unquote(match.group(1))
        if not url.startswith(BADGE_URL_PREFIX):
            errors.append(
                f"endpoint badge {url!r} does not point at the badge-data branch"
            )
            continue
        payload = url.removeprefix(BADGE_URL_PREFIX)
        if payload not in REQUIRED_PAYLOADS:
            errors.append(f"endpoint badge references unknown payload {payload!r}")
            continue
        referenced.add(payload)
    missing = [payload for payload in REQUIRED_PAYLOADS if payload not in referenced]
    if missing:
        errors.append("README is missing endpoint badges for: " + ", ".join(missing))
    if errors:
        print("Badge check failed:", file=sys.stderr)
        print(*[f"- {error}" for error in errors], sep="\n", file=sys.stderr)
        return 1
    print(
        f"All {len(REQUIRED_PAYLOADS)} README badges reference the badge-data branch."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=Path(__file__).resolve().parents[2]
    )
    return main_with_root(parser.parse_args().root)


if __name__ == "__main__":
    raise SystemExit(main())
