name: GitHub Actions security

on:
  pull_request:
    paths:
      - ".github/**"
      - "mise.toml"
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "mise.toml"

permissions:
  contents: read

jobs:
  zizmor:
    name: Audit GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # v4 -> 11d5960a326750d5838078e36cf38b85af677262
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      # v0.6.2 -> 3dc1ecc9bcb9e97.0.1e9b2c709687979e12987.0.197057.0.1
      - uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054
